# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='distrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votos.Distrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votos',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votos.Candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votos',
            name='valido',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
